image: docker:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- /bin/sh ci/docker_install.sh > /dev/null

build:
  stage: build
  tags:
    - privileged
  script:
  - 'echo "Using registry: ${REGISTRY_URL}"'
  - /bin/sh ci/build.sh
